AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: just-in-time-dev

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Environment:
  JITAPIID:
    Ref: JITAPI

Resources:
  JITAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      Name: just_in_time_api
      Tags:
        App: just-in-ti.me
        Environment: dev
  JITFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: just_in_time/
      Handler: just_in_time.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: JITAccessSecretsManager
              Effect: Allow
              Action:
                - secretsmanager:GetResourcePolicy
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:ListSecretVersionIds
              Resource: "arn:aws:secretsmanager:eu-central-1:891666753558:secret:JITKeys-jnrBoy"
      Events:
        GetUserdata:
          Type: HttpApi
          Properties:
            Path: /api/_userdata
            Method: get
            ApiId: JITAPIID
        PatchUserdata:
          Type: HttpApi
          Properties:
            Path: /api/_userdata
            Method: patch
            ApiId: JITAPIID
        DeleteUserdata:
          Type: HttpApi
          Properties:
            Path: /api/_userdata
            Method: delete
            ApiId: JITAPIID

Outputs:
  JITAPI:
    Description: "API Gateway endpoint URL for dev stage for JIT function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/dev/jit/"
  JITFunction:
    Description: "JIT Function ARN"
    Value: !GetAtt JITFunction.Arn
  JITFunctionIamRole:
    Description: "Implicit IAM Role created for JIT function"
    Value: !GetAtt JITFunctionRole.Arn
