AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: just-in-time-dev

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  JitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: just_in_time/
      Handler: just_in_time.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Sid: JITAccessSecretsManager
              Effect: Allow
              Action:
                - secretsmanager:GetResourcePolicy
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:ListSecretVersionIds
              Resource: "arn:aws:secretsmanager:eu-central-1:891666753558:secret:JITKeys-jnrBoy"
      Events:
        GetUserdata:
          Type: HttpApi
          Properties:
            Path: /api/_userdata
            Method: get
            ApiId: !Ref JitApi
        PatchUserdata:
          Type: HttpApi
          Properties:
            Path: /api/_userdata
            Method: patch
            ApiId: !Ref JitApi
        DeleteUserdata:
          Type: HttpApi
          Properties:
            Path: /api/_userdata
            Method: delete
            ApiId: !Ref JitApi
      Tags:
        App: just-in-ti.me
        Environment: dev
  JitApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev
      Name: just_in_time_api
      Tags:
        App: just-in-ti.me
        Environment: dev
Outputs:
  JitApiId:
    Description: Api ID of JitApi
    Value:
      Ref: JitApi
  JitFunction:
    Description: "JIT Function ARN"
    Value: !GetAtt JitFunction.Arn
  JitFunctionIamRole:
    Description: "Implicit IAM Role created for JIT function"
    Value: !GetAtt JitFunctionRole.Arn
