AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Function and API Gateway for just-in-ti.me.

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  env:
    Type: String
    Description: Environment of the deployment (Lowercase)
  Env:
    Type: String
    Description: Environment of the deployment
  Domain:
    Type: String
    Description: Base Domain for API Gateway of the deployment
    Default: api.just-in-ti.me

Resources:
  JitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "JitApiFunction${Env}"
      CodeUri: just_in_time/
      Handler: just_in_time.lambda_handler
      Runtime: python3.9
      Architectures:
        # - x86_64
        - arm64
      Policies:
        - Statement:
            - Sid: JITAccessSecretsManager
              Effect: Allow
              Action:
                - secretsmanager:GetResourcePolicy
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:ListSecretVersionIds
              Resource: "arn:aws:secretsmanager:eu-central-1:891666753558:secret:JITKeys-jnrBoy"
      Events:
        GetUserdata:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
            ApiId: !Ref JitApi
        PatchUserdata:
          Type: HttpApi
          Properties:
            Path: /
            Method: patch
            ApiId: !Ref JitApi
        DeleteUserdata:
          Type: HttpApi
          Properties:
            Path: /
            Method: delete
            ApiId: !Ref JitApi
      Tags:
        App: just-in-ti.me
        Environment: !Ref env
  JitApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref env
      Name: just_in_time_api
      Domain:
        Type: AWS::Serverless::HttpApiDomainConfiguration
        Properties:
          DomainName: !Ref Domain
      Tags:
        App: just-in-ti.me
        Environment: !Ref env
Outputs:
  JitApiId:
    Description: Api ID of JitApi
    Value:
      Ref: JitApi
  JitFunction:
    Description: "JIT Function ARN"
    Value: !GetAtt JitFunction.Arn
  JitFunctionIamRole:
    Description: "Implicit IAM Role created for JIT function"
    Value: !GetAtt JitFunctionRole.Arn
