AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  S3 bucket for Frontend Deployment

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Mappings:
  EnvMap:
    prod:
      BucketName: "jit-frontend-prod"
      Domain: "just-in-ti.me"
    dev:
      BucketName: "jit-frontend-dev"
      Domain: "dev.just-in-ti.me"

Parameters:
  env:
    Type: String
    Description: Environment of the deployment (Lowercase)

Resources:
  JitBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !FindInMap [EnvMap, !Ref env, BucketName]
      # PublicAccessBlockConfiguration:
      #   BlockPublicAcls: false
      #   BlockPublicPolicy: false
      #   IgnorePublicAcls: false
      #   RestrictPublicBuckets: false
      Tags:
        - Key: App
          Value: just-in-ti.me
        - Key: Environment
          Value: !Ref env
      WebsiteConfiguration:
        IndexDocument: index.html
        # RedirectAllRequestsTo: index.html

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Id: JitPublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref JitBucket
                - /*
      Bucket: !Ref JitBucket

  JitDNSEntry:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: "just-in-ti.me"
      #  !Sub
      #    - ${Domain}.
      #    - Domain: !Ref Domain
      Comment: Zone apex alias.
      RecordSets:
        - Name: !FindInMap [EnvMap, !Ref env, Domain]
          Type: A
          AliasTarget:
            HostedZoneId: "Z0300930209VNAOS1X0XR"
            DNSName: "s3-website-eu-central-1.amazonaws.com"
        - Name: !Sub
            - www.${Do}
            - Do: !FindInMap [EnvMap, !Ref env, Domain]
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !GetAtt JitBucket.DomainName

Outputs:
  WebsiteURL:
    Value: !GetAtt JitBucket.WebsiteURL
    Description: URL for website hosted on S3
