on:
  push:
    branches:
      - dev
jobs:
  deploy_dev_api:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: sam build
        working-directory: lambda
      - run: sam deploy --parameter-overrides env=dev --no-confirm-changeset --no-fail-on-empty-changeset --stack-name just-in-time-api-dev --s3-bucket conf-bucket-jit-api-dev --capabilities CAPABILITY_IAM --region eu-central-1
        working-directory: lambda
  deploy_dev_frontend:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM Dependencies
        working-directory: q-frontend
        run: npm i -g
      - run: npm list
      - name: Build Quasar Frontend
        run: quasar build
        working-directory: q-frontend
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Build SAM Template
        run: sam build
        working-directory: q-frontend
      - name: Deploy Frontend in S3 Bucket
        run: sam deploy --parameter-overrides env=dev --no-confirm-changeset --no-fail-on-empty-changeset --stack-name just-in-time-frontend-dev --s3-bucket conf-bucket-jit-frontend-dev --capabilities CAPABILITY_IAM --region eu-central-1
        working-directory: q-frontend
